### ISSUE TITLE
Check the foreign key structure and remove the transaction table

### ISSUE THREAD

**Issue by reneweteling** [reneweteling/beerbot#4]
- [x] Check the foreign key structure (add dependent's to relations, and db integrity)
- [x] Remove the transaction table / model etc. This feature is no longer necessary
- [x] Fix up the activeadmin DSL, for instance in some cases you dont see the user.

**Comment by gurjar-mehul** [comment]
Hello @reneweteling 

Here is pull request URL, 
https://github.com/reneweteling/beerbot/pull/6

Thanks
